urbanairship/urbanairship-cordova

- README.md
- src/android/CordovaAutopilot.java
Add option to have a sound associated with notification on Android.
> Push sound android

- src/android/build-extras.gradle
In order to be compatible with usage of the google analytics cordova plugin:
https://github.com/danwilson/google-analytics-plugin
> Use latest version of play services.

- Example/index.html
- plugin.xml
- src/android/CordovaAirshipReceiver.java
- src/android/CordovaAutopilot.java
- src/android/UAirshipPlugin.java
- src/android/UAirshipPluginManager.java
- src/android/events/ChannelEvent.java
- src/android/events/DeepLinkEvent.java
- src/android/events/Event.java
- src/android/events/InboxEvent.java
- src/android/events/PushEvent.java
- src/ios/UAirshipPlugin.h
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
Enables the ability to handle deep links triggered from in-app messages, landing pages, and the message center.
> Fire a deep link event when deep link action is called

- src/android/UAirshipPlugin.java
- src/ios/UAirshipPlugin.h
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
For issue https://github.com/urbanairship/phonegap-ua-push/issues/124
> [MB-1915] Add isAppNotificationsEnabled method

- src/android/CordovaAutopilot.java
Need it for the gimbal bridge.
> [MB-1555] Add airship ready intent

- www/UrbanAirship.js
Adds a custom event method that just wraps the custom event action
> [MB-1984] Add custom event method

- README.md
Update readme with cocoapods info.
> Update readme with cocoapods info.

- CHANGELOG
- COPYING
- MIGRATION.md
- jsdoc_readme.md
- src/android/CordovaAirshipReceiver.java
- src/android/CordovaAutopilot.java
- src/android/CordovaLandingPageView.java
- src/android/UAirshipPlugin.java
- src/android/UAirshipPluginManager.java
- src/android/events/ChannelEvent.java
- src/android/events/DeepLinkEvent.java
- src/android/events/Event.java
- src/android/events/InboxEvent.java
- src/android/events/NotificationOpenedEvent.java
- src/android/events/PushEvent.java
- src/ios/UAMessageViewController.h
- src/ios/UAMessageViewController.m
- src/ios/UAirshipPlugin.h
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
Release 6.4.0:
* Added support for configuring logging levels.
> Release 6.4.0

- CHANGELOG
- package.json
- plugin.xml
> Release 6.6.0

- src/android/UAirshipPluginManager.java
- src/android/events/RegistrationEvent.java
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
https://github.com/urbanairship/phonegap-ua-push/issues/205
Adds registrationToken to the registration events
> [MB-2531] Add registrationToken to registration events

- CHANGELOG
- package.json
- plugin.xml
- src/android/build-extras.gradle
> Release 6.9.3

- README.md
- scripts/create_sample.sh
- scripts/run_ci_tasks.sh
Add a Continuous Integration (CI) script to our Cordova repo.
We want to run CI on all pushes to the Cordova repo. We want it to also be run locally.
Ran it locally. Also tested on CI server, with PR and Push triggers.
Secrets have been reviewed to limit use in pull requests.
> [MOBILE-277] Add a CI task.

- CHANGELOG
- package.json
> Release 7.3.1

- src/android/CustomLandingPageActivity.java
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your pull request is reviewed as quickly and efficiently as possible.
I was thinking we did not use the new ENABLE_LOCAL_STORAGE metadata flag, but we are. This change just removes the redudent enabling of the local storage.
> [MOBILE-361] Enable local storage flag

- plugin.xml
Updates the plugin.xml version to match the version on package.json file
See #265 for additional information
> Updated version to match the package.json version

- CHANGELOG
- package.json
- plugin.xml
- src/android/build-extras.gradle
> Release 7.3.2

- src/android/UAirshipPlugin.java
> Missing import statement

- CHANGELOG
- README.md
- package.json
- plugin.xml
- src/android/build-extras.gradle
Manually tested iOS and Android.
> Release 7.3.3

- README.md
- src/android/PluginManager.java
- src/android/UAirshipPlugin.java
Updates the readme with JS takeOff and configure steps. Also fixed a takeOff error log due to calling takeOff on a bg thread on Android.
People want to control everything through JS instead of xml
> MOBILE-391: Document + Fix JS takeOff

- src/android/ConfigUtils.java
- src/android/CordovaAirshipReceiver.java
- src/android/CordovaAutopilot.java
- src/android/CordovaNotificationFactory.java
- src/android/CustomLandingPageActivity.java
- src/android/CustomMessageActivity.java
- src/android/CustomMessageCenterActivity.java
- src/android/events/DeepLinkEvent.java
- src/android/events/Event.java
- src/android/events/InboxEvent.java
- src/android/events/NotificationOpenedEvent.java
- src/android/events/NotificationOptInEvent.java
- src/android/events/PushEvent.java
- src/android/events/RegistrationEvent.java
- src/android/events/ShowInboxEvent.java
- src/ios/UACordovaPluginManager.h
- src/ios/UACordovaPluginManager.m
- src/ios/UAMessageViewController.h
- src/ios/UAMessageViewController.m
- src/ios/UAirshipPlugin.h
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
remove copyright ranges
class headers can be rangeless, we don't want to edit these every year.
> [MOBILE-462] remove copyright date ranges

- CHANGELOG
- package.json
- plugin.xml
Releasing before the 8.0 release to resolve  https://github.com/urbanairship/urbanairship-cordova/issues/302
> Release 7.6.0

- CHANGELOG
> [MOBILE-633] update changelog

- CHANGELOG.md
- package.json
- plugin.xml
> Release 9.0.1

- README.md
- scripts/create_sample.sh
- src/android/ConfigUtils.java
- src/android/CordovaAutopilot.java
- src/android/CordovaNotificationProvider.java
- src/android/CustomMessageActivity.java
- src/android/CustomMessageCenterActivity.java
- src/android/PluginLogger.java
- src/android/PluginManager.java
- src/android/UAirshipPlugin.java
- src/android/Utils.java
- src/android/build-extras.gradle
- src/android/events/Event.java
- src/android/events/InboxEvent.java
- src/android/events/NotificationOpenedEvent.java
- src/android/events/NotificationOptInEvent.java
- src/android/events/PushEvent.java
- src/android/events/RegistrationEvent.java
- src/android/events/ShowInboxEvent.java
Updates Android SDK to 12.1.
We need a modern version of our SDK to support new features.
Ran sample app, verified message center, named user, and tags work.
> Mobile 1043

- CHANGELOG.md
- README.md
Add to the changelog for the 10.0.0 release.
Process. Communications.
I looked at the commits for this release.
> Changelog for 10.0.0 release.

- plugin.xml
Update Cordova to iOS SDK 13.1.0
Using sample app
> Update Cordova to iOS SDK 13.1.0

- src/android/UAirshipPlugin.java
- src/ios/UAirshipPlugin.m
- www/UrbanAirship.js
Add number channel attribute support to Cordova plugin for Android and iOS.
Support the attributes.
Manually set through javascript. Checked result using cool new API endpoint I got from Weasel.
> [MOBILE-1280] Add number attribute support to Cordova

- CHANGELOG.md
- plugin.xml
Update the repo for release 10.1
Need to roll out new functionality.
Local CI. Changes are limited to changelog and version number.
> [MOBILE-1291] Release 10.1

- package.json
- plugin.xml
Update some more version strings in repo.
Confluence docs were out-of-date
Local CI
I updated the [Confluence docs](https://urbanairship.atlassian.net/wiki/spaces/MOBILE/pages/53711200/PhoneGap+Cordova).
> [MOBILE-1201] Update version strings

- .github/workflows/release.yaml
- scripts/check_version.sh
- scripts/upload_docs.sh
I copied the react deploy and made it work with cordova
> [MOBILE-1342] Move deploy to github actions

- .github/workflows/release.yaml
- CHANGELOG.md
Adds creating a github release during our release flow. Reformats the changelog to make it easier to pull the release notes.
> [MOBILE-1345] Add github release

- CHANGELOG.md
- package.json
- plugin.xml
> Release 10.1.1

- plugin.xml
- src/android/CordovaAutopilot.java
- src/android/UAirshipPlugin.java
- src/android/build-extras.gradle
Updates latest Android SDK. Removes theme on manifest entries to make it easier to theme. The message center will now pick up app theme. App compat was not needed since we are not using it, but apps should be able to add it back if they want it.
Latest SDK!
Ran sample app
> [MOBILE-1506] Update Android SDK 13.1.0

- CHANGELOG.md
- package-lock.json
- package.json
- plugin.xml
> Release 10.1.2

- CHANGELOG.md
- package.json
- plugin.xml
Update the iOS SDK to version 14.2.2
To stay updated
By running sample app
> [MOBILE-2061] Update Cordova to iOS SDK 14.2.2

- scripts/update_version.sh
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/build-extras.gradle
Tested manually on a device/emulator with pushes and general poking around. I also made some changes to the update_version script which should make it easier for us to keep the version numbers up to date in the various modules.
> [MOBILE-2141] update SDK versions to 14.3.0

- package.json
- urbanairship-hms-cordova/README.md
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
Adding the HMS module to Cordova
So Cordova apps can support HMS devices
By adding the plugin to the sample app and verifying that it was correctly implemented
> [MOBILE-2140] Add HMS module to Cordova

- .github/workflows/release.yaml
- CHANGELOG.md
- scripts/create_sample.sh
- scripts/update_version.sh
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/scripts/before_build.js
- urbanairship-hms-cordova/scripts/lib/android.js
- urbanairship-hms-cordova/src/android/build-extras.gradle
Prepare plugin for release 12.2.0.
Also update the scripts
To release cordova plugin 12.2.0
> [MOBILE-2142] Release 12.2

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
Update iOS SDK to 16.0.2
Update the framework version to 13.0.1
Update changelog
Build and run OK
> [MOBILE-2632] Release 13.0.1

- CHANGELOG.md
- Example/index.html
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/CordovaAutopilot.java
- urbanairship-cordova/src/android/PluginManager.java
- urbanairship-cordova/src/android/UAirshipPlugin.java
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-cordova/src/android/events/PreferenceCenterEvent.java
- urbanairship-cordova/src/ios/UACordovaPluginManager.h
- urbanairship-cordova/src/ios/UACordovaPluginManager.m
- urbanairship-cordova/src/ios/UAirshipPlugin.h
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-cordova/src/ios/events/UACordovaPreferenceCenterEvent.h
- urbanairship-cordova/src/ios/events/UACordovaPreferenceCenterEvent.m
- urbanairship-cordova/www/UrbanAirship.js
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
Prepare the cordova 13.3.0 release
- Expose preference center config 
- Expose editing subscription lists, 
- Update the plugin versions
Manual testing
> Mobile 2870 release 13.3.0

- urbanairship-cordova/src/android/UAirshipPlugin.java
- urbanairship-cordova/src/ios/UAirshipPlugin.h
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-cordova/www/UrbanAirship.js
Adds enableUserNotifications method
To expose the native SDK feature
Manual test
> add enableUserNotifications method

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/PluginManager.java
- urbanairship-cordova/src/android/UAirshipPlugin.java
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/app-build-extras.gradle
- urbanairship-hms-cordova/src/android/build-extras.gradle
Changes:
- Return the raw config for preference center
- Fixed use custom UI on Android. It was storing it in the wrong place
- Fixed subscription lists on iOS
- Removed use of deprecated NamedUser 
- Updated latest Android SDK
- Removed targetSdkVersion and force resolution of app compat
> Release 14.0.0

- urbanairship-cordova/src/android/UAirshipPlugin.java
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-cordova/www/UrbanAirship.js
Fixes setting named user to null. Testing on both iOS and Android.
> [GH-395] Allow setNamedUser to null

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
- Updated Android SDK to 16.6.1.
- Updated iOS SDK to 16.8.0.
Sample app
> Update to latest SDKs

- .github/workflows/CI.yaml
- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
Update to Android SDK 16.7.4 and iOS SDK 16.9.3
Keep the framework updated and fix versions conflict due to our last android-gimbal-adapter version.
Manual test. Build and run OK. Versions conflict fixed.
> [MOBILE-3269] Update to latest SDKs

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/PluginManager.java
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-cordova/src/ios/UACordovaPluginManager.m
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
Update the SDKs and add support for custom domain
Keep up to date
Manual tests
> [MOBILE-3381] Update to latest SDKs

- Example/myMessageCenterStyleConfig.plist
- config_sample.xml
- scripts/create_sample.sh
- urbanairship-cordova/src/ios/UACordovaPluginManager.h
- urbanairship-cordova/src/ios/UACordovaPluginManager.m
- urbanairship-cordova/src/ios/UAirshipPlugin.h
- urbanairship-cordova/src/ios/UAirshipPlugin.m
- urbanairship-cordova/www/UrbanAirship.js
Add a way to set message center styling.
Sample app
> add support for message center  config style

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
> Release 14.7.0

- CHANGELOG.md
- README.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
Bump SDK versions : Android SDK to 16.9.0 and iOS SDK to 16.11.2.
> Prepare release 14.8.0

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-accengage-cordova/src/android/build-extras.gradle
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/build-extras.gradle
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
- urbanairship-hms-cordova/src/android/build-extras.gradle
This should fail until the SDK release finish deploying
> Release 14.10.0

- CHANGELOG.md
- urbanairship-accengage-cordova/package.json
- urbanairship-accengage-cordova/plugin.xml
- urbanairship-cordova/package.json
- urbanairship-cordova/plugin.xml
- urbanairship-cordova/src/android/UAirshipPlugin.java
- urbanairship-hms-cordova/package.json
- urbanairship-hms-cordova/plugin.xml
Removes Play Services error message.
This is about an escalation where Huawei users get an error dialog saying that their device doesn’t support Google services.
> [MOBILE-4058] remove play services error message

- cordova-airship/src/android/build-extras.gradle
compatibility with cordova-android@13
https://cordova.apache.org/announcements/2024/05/23/cordova-android-13.0.0.html
https://github.com/apache/cordova-android/pull/1678/files#diff-3dc11ca3a71905f437e1e170f963e9854da27943efcff23bf87bfe87abeda513L53
> Сompatibility with cordova-android@13
