urbanairship/urbanairship-cordova

README.md
plugin.xml
scripts/copy_resources.js
scripts/remove_files.js

Remove need to manually delete custom_rules.xml
Copy resources for iOS
Execute hook on build and run
Don't try to unlink a file that doesn't exist

Remove the need to do so many manual steps on 'phonegap plugin add'

---

plugin.xml

It looks like the Cordova project has changed the dependency id of `cordova-plugin-device` from `org.apache.cordova.device` to `cordova-plugin-device`. We need to update our dependency id to match it.
https://github.com/apache/cordova-plugin-device/blob/master/plugin.xml#L24

Update cordova-plugin-device dependency id

---

scripts/copy_resources.js

The path to the plugin has changed, and errors happen when you try to build or add the iOS platform.
I really appreciate that you work on and maintain the plugin, but its a bit frustrating to run into such a trivial bug.

Update plugin path to urbanairship-cordova

---

src/android/UAirshipPlugin.java

When starting new activity using the application context, Android app will crash if the start intent does not have FLAG_ACTIVITY_NEW_TASK flag set.

Sending Activity context to PlayServicesUtils#handleAnyPlayServicesError

---

src/ios/UAirshipPlugin.m

Return the device token along with the channel ID from the urbanairship.registration event.  This is helpful to be able to send the device token to the back end server to be used with the UA API.

Return device token from UARegistrationDelegate registrationSucceededForChannelID

---

scripts/copy_resources.js

Config parser is totally broke with latest cordova. this allows it to find it by module rather than relative path.

Fix config parser for 4.5.0 and Cordova-commons

---

CHANGELOG
package.json
plugin.xml

Update Android Urban Airship SDK to use latest version of play services.
Testing:
* Ran Sample on Nexus 5x and received push notification and rich push messages.

[MB-1859] Release 5.3.1

---

src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Does not include the helper methods for setting advertising ids and properties.

Adds the ability to set an associated identifier for use with Connect.

---

README.md
jsdoc_readme.md
src/android/CordovaAutopilot.java

Allows configuring the plugin to use a custom notification large icon.
// config.xml
``
`<preference name="com.urbanairship.notification_large_icon" value="ua_ic_close" />`
Example where the large icon is `X`:

[MB-1962] Set notification large icon.

---

src/ios/UAirshipPlugin.m

Matches Androids implementation and the push API restrictions. Fixes issue #135

Do not force iOS deep links to be valid URLs

---

src/ios/UAirshipPlugin.m

Update UAPushNotificationDelegate methods.
Testing:
[Log] Received push: Alert - efac3925-8744-4012-985d-099b782e4d57 (index.html, line 23)
[Log] Device pause! (index.html, line 72)
[Log] Device resume! (index.html, line 60)
[Log] Launched from push: Alert - 2ffdef46-b332-4994-9632-aff44151fd40 (index.html, line 32)
[Log] Firing document event: urbanairship.registration (UrbanAirship.js, line 121)
[Log] Reg Success: 3f24d844-1242-4841-81d9-2c385681812d (index.html, line 41)

Update UAPushNotificationDelegate methods.

---

README.md
jsdoc_readme.md
src/ios/UAirshipPlugin.m

Added iOS 10 foreground presentation support.
Specify the optional default foreground presentation options for iOS 10 via the config.xml:
```
<preference name="com.urbanairship.ios_foreground_notification_presentation_alert" value="true"/>
<preference name="com.urbanairship.ios_foreground_notification_presentation_badge" value="true"/>
<preference name="com.urbanairship.ios_foreground_notification_presentation_sound" value="true"/>
```
Testing:
* Tested foreground push notifications with various presentation options on iOS 10.0.2 iPod

[MB-1976] Added iOS 10 foreground presentation support.

---

Example/index.html
plugin.xml
src/android/CordovaAirshipReceiver.java
src/android/UAirshipPlugin.java
src/android/UAirshipPluginManager.java
src/android/events/NotificationOpenedEvent.java
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Fire `urbanairship.notification_opened` event when notification opened.
Testing:
* Android log snippet
UrbanAirship.js:121 Firing document event: urbanairship.notification_opened
index.html:32 Notification opened: Alert - 4de9441c-a20e-4f5d-87ae-eff17138c2e8
* iOS log snippet
[Log] Firing document event: urbanairship.notification_opened (UrbanAirship.js, line 121)
[Log] Notification opened: Alert - 83664524-f671-4e21-ac3a-1586d913f57c (index.html, line 32)

[MB-1985] Fire event when notification opened.

---

README.md
package.json

Hi all,
Per [SUPPORT-5868](https://tofurkey.urbanairship.com/browse/SUPPORT-5868):
The support@urbanairship.com email address is listed on the phonegap-ua-push repository on Github. We do not want this listed on a public repository as email support is reserved for paying customers. We direct any free customers to the forums, so I think it makes sense to list http://support.urbanairship.com/ in place of the support email address.
I only modified the README.md and the package.json file. I just removed the bugs field from the package.json. I can add it back in there if need be, and just replace 'email' with 'url' and make the url the support website.

Removed support email address from repo

---

README.md

Update readme to require cordova-cli 6.4.0
Note: I think we can ignore the check failure, since this is a one line non-code change in readme file. I believe it is due to the new build machine and will fix it when I get into the office.

Require cordova-cli 6.4.0

---

README.md
src/ios/UAirshipPlugin.m

Fixed deprecation warnings for iOS plugin and updated readme.
Testing:
* Verified quiet time enabled/disabled with specified times on iOS 10.1.1 iPod device

[MB-2057] Fixed deprecation warnings for iOS plugin and update readme

---

README.md
jsdoc_readme.md
src/android/CordovaAutopilot.java
src/ios/UAirshipPlugin.m

Configure logging levels for Android and iOS:
* Set default production log level to `error`
* Set default development log level to `debug`
* Optionally set log levels via config.xml:
```
<preference name="com.urbanairship.development_log_level" value="none | error | warn | info | debug | verbose" />
<preference name="com.urbanairship.production_log_level" value="none | error | warn | info | debug | verbose" />
```
Testing:
* Tested on iPod and nexus5x and verified logs

[MB-2081] Configure logging levels.

---

CHANGELOG
package.json
plugin.xml
src/android/build-extras.gradle

Release 6.5.0
* Update Android Urban Airship SDK to use latest version of play services.
* Updated Android Urban Airship SDK to 8.2.5
Testing:
* Ran sample on Android Nexus 5x device and received push. Verified console log UA Lib version = 8.2.5

Release 6.5.0

---

plugin.xml
src/android/CustomLandingPageActivity.java
src/android/CustomMessageActivity.java
src/android/CustomMessageCenterActivity.java
src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

New methods:
* `dismissMessageCenter` closes the message center from `displayMessageCenter`
* `dismissInboxMessage` closes the inbox message from `displayInboxMessage`
* `dismissOverlayInboxMessage` closes the overlay inbox message from `overlayInboxMessage`
Testing:
* Tested on Android Nexus5x and iOS iPhone.

MB-2078: Dismiss Message Ctr, Inbox Message and Overlay Inbox Message

---

src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Hi UA team,
Thanks again for the recent `.dismiss()` features - that is going to let us take our deep-links to the next level :+1: 
I have a bit of a non-standard use case here, so I was hoping to get your input.
**Short version:**
Our app uses **multiple cordova webviews**, a "main" webview, and a secondary "child" webview that sometimes takes over.
Currently, **once the second child webview is dismissed, the main webview no longer receives UA document events.**
So, here are some small changes for your consideration. We're currently using them successfully.
-----
Long version:
In the `www/UrbanAirship.js` file, there is a call to the native `registerListener` method, which occurs once the cordova `deviceready` event fires.
This works great for any number of newly-created cordova …

Multiple webviews - re-attaching event listeners

---

src/android/UAirshipPlugin.java

Checks to make sure the message ID is not null or empty before setting the intent

[CE-3539] Fix displayMessageCenter on Android

---

README.md
jsdoc_readme.md
src/android/CordovaAutopilot.java

Adds a workaround for the AAPT2 bug. We now allow the sender ID to be prefixed with `sender:` so the android build system will not parse the number string. See https://issuetracker.google.com/issues/69347762 and https://github.com/urbanairship/phonegap-ua-push/issues/206 for more details

[GH-206] Add workaround to AAPT2 issue

---

plugin.xml
src/android/CordovaAirshipReceiver.java
src/android/UAirshipPluginManager.java
src/android/events/NotificationOpenedEvent.java
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Adds notification response info to the open event.
I also fixed a few issues when I was testing. Lots of main thread checker warnings for iOS and build issues for Android. 
Testing:
- Android registration event, notification opens, etc..
- iOS registration event. Still need to test a interactive notification.

[MB-2531] Add response info to notification event

---

src/android/events/PushEvent.java

Android's PushEvent is throwing an exception on `getEventData` while looping through `pushBundle`. We're passing `google.ttl` as an integer, but calling `getString` on it.
This gets the value as and integer and converts to a string before adding to `extras`.

update getEventData to handle integer value

---

src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

This is a PR that addresses the same stuff as https://github.com/urbanairship/urbanairship-cordova/pull/227, but with a structure we'd prefer.
* Adds title and subtitle to top level push event object. (subtitle maps to "summary" on android for historical reasons)
* APS dictionary on iOS now goes in its own top-level field as well, in case folks want access to the raw push data for whatever reason
Note: I'm not sure how best to document this change, aside from making a note in the CHANGELOG. Platform extdocs?

[MOBILE-200] title and subtitle, aps push event fields

---

README.md
config_sample.xml
src/android/build-extras.gradle

I had to do some gradle magic to make this work, but it seems to do the trick. This makes FCM the default going forward, and also does away with the need for users to prefix the sender ID because google-services.json should have all the credendtials they need. Also bumping the cordova command line tool requirements to 7.0, due to changes in android app structure that complicate the specification of resource files.

[MOBILE-177] android SDK 9.3, FCM support

---

src/ios/UAirshipPlugin.m

This is just feature parity with the android plugin, so that background notifications will result in a push event getting created and enqueued into the JS layer. No SDK bindings were harmed in the making of this pull request.

[MOBILE-199] generate push events from background push on iOS

---

CHANGELOG
package.json
plugin.xml

Note: I assume we're releasing iOS 9.2.1 today, and if so I'll make sure to drop the new iOS SDK in before pulling the trigger on this release. Otherwise, we can modify the CHANGELOG accordingly.

[release-7.1] CHANGELOG, version bumps

---

plugin.xml
src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m

Allows takeOff to be called from JS on iOS.
The majority of this change is breaking apart the UAirshipPlugin class. I moved all the takeOff, config, and Airship wiring into UACordovaPluginManager.

[MOBILE-215] Enable takeOff from JS for iOS

---

src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

This adds a setter for presentation options that's accessible from the JS layer/
These changes are necessary for users to dynamically set the presentation options from the JS layer and eventually move away from setting presentation options in the config entirely. 
Added the new presentation options setter call to the quietTimeEnabled button (temporarily) and traced execution through the expected plugin and plugin manager calls.

[MOBILE-237] Cordova: Add setter for foreground presentation options

---

src/android/ConfigUtils.java
src/android/PluginManager.java
src/android/UAirshipPlugin.java

All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your pull request is reviewed as quickly and efficiently as possible.
Adds explicit types to any `<>` declarations to allow older Cordova Android (<= 6.4.0) to build
Changes `cordova.getContext()` to `cordova.getActivity().getApplicationContext()`.
To allow builds against `cordova-android@<=6.4.0`
Forked the repo, made the changes, built the app.

Specify inferred types for backwards compatibility, fix reference to Context

---

src/android/CordovaAutopilot.java
src/android/UAirshipPlugin.java

Prevents early takeOff (before application.onCreate)
Makes our plugin compatible with APK wrappers.
Ran the sample.

[MOBILE-362] Prevent early takeOff

---

src/android/CordovaNotificationFactory.java
src/android/UAirshipPlugin.java
src/android/events/PushEvent.java
src/ios/UACordovaPluginManager.h
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

This adds the ability to get active (posted) notifications to our cordova plugin, as well as clear notifications, either wholesale or by identifier. The overall structure of the solution is modeled after our react module, which I borrowed a bit of code from where appropriate.
The way we've been doing this in react has been to pass up notification identifiers as strings on Android, and when appropriate affixing the notification tag if it has one. The resulting strings look like "<ID>:<TAG>", and have to be re-parsed into their constituent parts when calling getActiveNotifications. This has the advantage of making a relatively uniform API, since iOS notifications have UUIDs for identifiers. In order to do this I deprecated the notification_id field in the push event and added a …

[MOBILE-406] active notification API

---

src/android/CordovaAutopilot.java
src/android/PluginManager.java
src/android/events/ShowInboxEvent.java
src/ios/UACordovaPluginManager.m
www/UrbanAirship.js

This adds a showInbox event to both iOS and Android that gets emitted if the default auto displaying inbox is disabled. 
To achieve functional parity with other similar plugins.
Ran the sample.

[MOBILE-412] Add showInbox event to iOS and Android implementations

---

src/android/ConfigUtils.java
src/android/PluginManager.java
src/android/UAirshipPlugin.java
src/android/Utils.java

All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your pull request is reviewed as quickly and efficiently as possible.
Adds explicit types to diamond operators and removes string switch to allow plugin to build against older Cordova projects
1.6 does not support implied types in diamond operators or string switches
Created a fork, made the changes, built a legacy project using these changes, verified the project worked.
ℹ If applicable, please provide screenshots here.
ℹ Please provide any additional notes for the reviewer here.

Fix: Maintains 1.6 compatibility for older Cordova projects

---

CHANGELOG
README.md
package.json
plugin.xml
scripts/run_ci_tasks.sh
src/android/build-extras.gradle

Adds Java6 CI check and an option to disable the GoogleServicesPlugin if another plugin is also adding it.
Doing a release since the README is being updated with the new gradle option.

Release 7.5.4

---

README.md
src/android/CordovaAutopilot.java
src/ios/UACordovaPluginManager.m

These changes add support for custom categories to facilitate customizing the buttons that appear inside interactive notifications. 
These changes are necessary to customize interactive notifications with buttons on the cordova platform. Prior to this work, one could only use the provided categories when choosing button types interactive notifications.
Manually tested on both iOS and Android using the following payload:
https://gist.github.com/crow/144426d519ec41881a2f945887da7012
Documentation is here:
https://github.com/urbanairship/extdocs/pull/2842
Work is essentially the same as the react-native plugin here:
https://github.com/urbanairship/react-native-module/pull/179

[MOBILE-593] notification button/categories support

---

plugin.xml
src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAirshipPlugin.m
src/ios/events/UACordovaDeepLinkEvent.h
src/ios/events/UACordovaDeepLinkEvent.m
src/ios/events/UACordovaEvent.h
src/ios/events/UACordovaInboxUpdatedEvent.h
src/ios/events/UACordovaInboxUpdatedEvent.m
src/ios/events/UACordovaNotificationOpenedEvent.h
src/ios/events/UACordovaNotificationOpenedEvent.m
src/ios/events/UACordovaNotificationOptInEvent.h
src/ios/events/UACordovaNotificationOptInEvent.m
src/ios/events/UACordovaPushEvent.h
src/ios/events/UACordovaPushEvent.m
src/ios/events/UACordovaRegistrationEvent.h
src/ios/events/UACordovaRegistrationEvent.m
src/ios/events/UACordovaShowInboxEvent.h
src/ios/events/UACordovaShowInboxEvent.m

These changes change how we package events to facilitate pending event storage. This matches the android implementation for the most part. Prior to this work, pending events were not being stored.
These changes are necessary to improve event reliability in situations where events would otherwise be dropped before the listener was ready to receive notifications.
This potentially addresses the following issue.
https://github.com/urbanairship/urbanairship-cordova/issues/302
Manually tested the sample.
The deep link event has a slightly different structure than the rest. This is because the way its data payload is constructed is relatively simple. In future work, we should move all the data management logic from the plugin manager to the events themselves. I've excluded said work from this pr …

[MOBILE-657] store pending events 

---

src/ios/UAirshipPlugin.m

Adds trace logging to the primary (non-helper) method calls, listener setting and event firing and adds debug logging to takeOff and plugin initialization.
To make the plugin easier to debug.
Built/ran cordova sample

[MOBILE-627] add more logging

---

src/android/PluginManager.java
src/android/UAirshipPlugin.java

Allows setting the default notification channel ID in preferences both directly and from the config.
To allow setting the default notification channel ID.
generating, running the android sample

[MOBILE-404] Allow setting the default notification channel ID

---

src/android/CordovaAutopilot.java

These changes adds support for custom notification channels. It uses the same approach as adding the notification button groups. This means the custom notification channels are loaded from XML.
To support custom notification channels.
Ran the sample with changes in place. Cross referenced with notification button groups and react-native implementation.
This won't pass tests until the following repo is public:
https://github.com/urbanairship/airship-location-cordova/tree/master/src
Extdocs documentation forthcoming.

[MOBILE-402] adds support for custom notification channels

---

www/UrbanAirship.js

This updates the Cordova plugin js api docs to let users know location functionality now requires AirshipLocationKit. I thought about including the link to the eventual airship-location-cordova plugin, but figured that since we mention this in the location docs link provided, doing so would be redundant and potentially misleading if we ended up renaming/altering the plugin location.

[MOBILE-632] update js location interface with new dependency info

---

package-lock.json
package.json
www/UrbanAirship.js

The last Cordova plugin update introduced a regression causing incomplete documentation output for TagGroupEditor. That change was also, in part, an attempt to deal with incomplete (missing) output for the main UrbanAirship module. Here's what I think was going on:
Moving the module annotation to the top of the file got the docs for the main module to generate correctly, but at the expense of the TagGroupEditor. I think that change wasn't a fix so much as it shifted the problem around. In my own testing, after reverting that change, I managed to boil it down to the way the script was run. Running the jsdoc command manually resulted in the correct output, and running it via `npm run` resulted in the broken output. The two versions of jsdoc were otherwise identical.
The one thing that …

[MOBILE-919] fix jsdoc regression

---

CHANGELOG.md
README.md
config_sample.xml
package-lock.json
package.json
plugin.xml
src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAirshipPlugin.m
src/ios/events/UACordovaShowInboxEvent.m

This is mostly updating the plugin and podspec versions, with a few fixes for the deprecation warnings that come with the push -> channel refactor, as well as some iOS 13 stuff. I also had to bump the minimum SDK version of the sample to 11.0 so that the SDK pod would install properly. 
While I was looking, I also cleaned up a variety of compiler and analyzer warnings such as:
* missing nullability annotations
* dictionary values that might be accidentally nil (which would cause crashes)
* the overlay inbox message method, which was accidentally recursing into itself instead of calling its helper
Manual testing is in progress but no surprises so far.
Note: because of the current CI issues, and because it would be a gnarly rebase otherwise, I'm temporarily setting this up to merge into the …

MOBILE-896 Update cordova plugin to iOS SDK 12.0

---

CHANGELOG.md
README.md
config_sample.xml
package-lock.json
package.json
plugin.xml
src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
src/ios/events/UACordovaNotificationOpenedEvent.h
src/ios/events/UACordovaNotificationOpenedEvent.m
src/ios/events/UACordovaNotificationOptInEvent.h
src/ios/events/UACordovaNotificationOptInEvent.m
src/ios/events/UACordovaPushEvent.h
src/ios/events/UACordovaPushEvent.m
src/ios/events/UACordovaRegistrationEvent.h
src/ios/events/UACordovaRegistrationEvent.m
src/ios/events/UACordovaShowInboxEvent.m

We have a few events using `eventWithData:` as a convenience constructor, and this has resulted in a situation where the plugin manager needs to know a bit too much about the shape of event data for its own good. This PR refactors those classes to take only the information they need to construct their own event data internally. Aside from the constructor changes, most of the diff is just helper methods being moved around. There's also a minor change to the opt-in event format that I'll leave a comment on below.
I'm still putting this through its paces as far as manual testing goes. In the meanwhile, have a look and see if this all makes sense.

[MOBILE-663] event constructor refactor

---

plugin.xml
src/ios/.gitignore
src/ios/UACordovaPluginManager.h
src/ios/UACordovaPluginManager.m
src/ios/UAMessageViewController.h
src/ios/UAMessageViewController.m
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
src/ios/events/UACordovaNotificationOpenedEvent.m
src/ios/events/UACordovaNotificationOptInEvent.h
src/ios/events/UACordovaPushEvent.h
www/UrbanAirship.js

- Updates the iOS SDK to 13.0.4
- Removes overlay inbox message functionality since its no longer easily done in the SDK
Sample test. Manually verified message center calls still work.

[MOBILE-1042] Update to iOS 13.0.4 SDK

---

package.json
plugin.xml
src/android/CordovaAutopilot.java
src/ios/UACordovaPluginManager.m
update_version.sh

Adds cordova plugin tracking so we can tell people use cordova. I made it so the version is supplied through the plugin.xml in either the Info.plist or as metadata in the manifest. Then the plugins will pull from the right place and track the extension. "0.0.0" is the default value if the version is unavailable for whatever reason.
Helps us identify what versions of cordova plugin are in the wild.
Manually tested it.

[MOBILE-1142] Add cordova plugin version tracking

---

src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Adds channel attribute support.
Gotta segment.
Ran sample app on both iOS and Android. Triggered attributes through the console and verified the right request was being generated.

[MOBILE-1203] Add channel attribute support

---

src/android/build-extras.gradle

Update Android SDK version to 12.2.0
To keep cordova module up to date
With a sample app, by looking at the SDK version loaded

[MOBILE-1277] Update Android SDK version

---

Example/index.html
src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Add screen tracking to Cordova
Manual tests, verified that the method is called on iOS and Android

[MOBILE-1290] Add screen tracking

---

scripts/check_plugin_version.sh
scripts/run_ci_tasks.sh

Add plugin version check to cordova CI
Because we have 4 different places where we have to version our cordova plugin and it will be safer to have this check in the CI
By testing it manually with the CI script.
The script can be used outside of the CI too.

[MOBILE-1344] Add plugin version check to CI

---

README.md

There's a place in the docs where we mention that an exit code of 1 when installing the plugin can indicate you need to do a pod repo update. There's another way you can get that exit code, which is where the iOS platform is set up with a lower minimum dependency than the plugin. There are a few ways that can happen, one of which is a known bug in cordova-ios, as well as just neglecting to set the minimum target version in config.xml. For a more in depth explanation see https://urbanairship.atlassian.net/browse/MOBILE-1450
I updated the README to make this more clear, and I also added a deployment target line to the example config.xml in the README. One downside of this is that we'll need to stay on top of updating that number when we do major SDK updates, but IMO that's better than not …

[MOBILE-1472] mention minimum deployment target issues in README

---

src/android/UAirshipPlugin.java

Change method routing algorithm from reflection of the action name to a big switch on the action name.
Reflection was causing issues with proguard.
Local builds and tests of the Cordova sample app.

[MOBILE-1510] Fix proguard issues with Cordova

---

plugin.xml
src/ios/UACordovaPluginManager.h
src/ios/UAMessageViewController.h
src/ios/UAMessageViewController.m
src/ios/UAirshipPlugin.m

Updates iOS SDK to 13.3.0. The biggest change is the message view deprecations. I copied most the changes from DefaultSplitViewController. There are few things we could do to make it easier to implement without as much duplicate code in the future, like maybe an MessageViewErrorHandler.
Updates latest iOS SDK. 
Ran sample on both iOS 11 and 13 simulators.

[MOBILE-1505] Update iOS SDK to 13.3.0

---

src/android/UAirshipPlugin.java
src/ios/UAirshipPlugin.h
src/ios/UAirshipPlugin.m
www/UrbanAirship.js

Adds a method to edit named user attributes
To keep the cordova plugin up to date with the native features
In the logs
```
2020-05-27 15:59:49.352 3191-3395/com.urbanairship.sample D/UALib-Cordova: Plugin Execute: editNamedUserAttributes
2020-05-27 15:59:49.352 3191-3395/com.urbanairship.sample D/UALib-Cordova: Editing named user attributes: [{"action":"set","value":"Rico","key":"nickname","type":"string"}]
2020-05-27 15:59:49.353 3191-4868/com.urbanairship.sample V/Test - UALib: PreferenceDataStore - Saving preference: com.urbanairship.nameduser.ATTRIBUTE_MUTATION_STORE_KEY value: [[{"timestamp":"2020-05-27T14:19:44","value":"Ulrich's phone","key":"device_name","action":"set"}],[{"timestamp":"2020-05-27T18:30:16","value":"Ulrich's …
```

[MOBILE-1566] Add named user attributes

---

CHANGELOG.md
package.json
plugin.xml
src/android/build-extras.gradle

Update cordova plugin as a patch (12.0.1).
Then Android SDK to 14.0.1 and iOS SDK to 14.1.2.
To keep cordova module up to date.
Build and run Android and iOS.

Update Cordova module and Android and iOS SDK version

---

www/UrbanAirship.js

I've noticed this 'cordova' was misspelled 'cardova' in this file.
It seems that it is then been used at the following line:
`cordova.fireDocumentEvent(e.eventType, e.eventData)`

FIX cordova spelling

---

.github/workflows/release.yaml
urbanairship-cordova/package.json

This fixes jsdoc output path in order to the upload_docs script to work.
I think that error comes from the merge of all our cordova repositories.
To make the upload_docs script work again and finally release cordova
Just generating the docs in local

Fix jsdoc out path

---

.github/workflows/CI.yaml
.github/workflows/release.yaml

Updates to the new modular GCP setup action.
Edit: also added a workaround for `dx` not being included in `build-tools:31.0.0`, which was causing the Android CI job to fail.
So that deploys continue working.
Doing it live, but tested the new action in a private repo and it installed the GCP CLI utils without issue.

[MOBILE-2438] Update setup-cloud action in release workflow

---

urbanairship-accengage-cordova/plugin.xml
urbanairship-accengage-cordova/src/android/build-extras.gradle
urbanairship-cordova/plugin.xml
urbanairship-cordova/src/android/build-extras.gradle
urbanairship-cordova/src/ios/events/UACordovaPushEvent.m
urbanairship-hms-cordova/src/android/build-extras.gradle

Update sdk version and fix notification response crash.
Alert is not necessary a dictionary, it can be a string.
Patch for a crash.
Build and run. Then test a push without any title or subtitle and verify there is no crash anymore

[MOBILE-2679] Update sdk version and fix notification response crash

---

.github/workflows/CI.yaml
.github/workflows/release.yaml
urbanairship-cordova/src/ios/UACordovaPluginManager.m

Set the push as enabled at launch if the config said so.
We used to set push as disabled at launch if the config enable_push_onlaunch is false.
That config field should only enable pushs at launch, not disable them.
Manual tests

[MOBILE-2800] fix push enabling on launch

---

urbanairship-cordova/src/android/CordovaAutopilot.java

Emits events for silent pushes on Android. Pushes that result in a notification will generate a push received event in the notification listener. 
I still need to verify it.

[GH-389] Fix silent push events on Android

---

urbanairship-cordova/src/android/CordovaNotificationProvider.java
urbanairship-cordova/src/android/PluginManager.java
urbanairship-cordova/src/android/UAirshipPlugin.java
urbanairship-cordova/src/android/Utils.java
urbanairship-cordova/src/ios/events/UACordovaPushEvent.m
urbanairship-cordova/www/UrbanAirship.js

Adds actions to the push message and a way to enable/disable foreground display on Android. Verified on iOS and Android.
We should eventually add the foreground control flag to the Android SDK.

[GH-393] Adds actions and foreground display control to Android

---

urbanairship-cordova/src/android/UAirshipPlugin.java
urbanairship-cordova/src/ios/UAirshipPlugin.h
urbanairship-cordova/src/ios/UAirshipPlugin.m
urbanairship-cordova/www/UrbanAirship.js

This PR adds locale override methods: setCurrentLocale, getCurrentLocale and resetLocale.
Matching other frameworks + customer demand
Tested manually.

[MOBILE-3060] Add locale override methods

---

CHANGELOG.md
urbanairship-accengage-cordova/package.json
urbanairship-accengage-cordova/plugin.xml
urbanairship-accengage-cordova/src/android/build-extras.gradle
urbanairship-cordova/package.json
urbanairship-cordova/plugin.xml
urbanairship-cordova/src/android/build-extras.gradle
urbanairship-hms-cordova/package.json
urbanairship-hms-cordova/plugin.xml
urbanairship-hms-cordova/src/android/build-extras.gradle

Patch release that fixing Contact update merging order, improves Scene/Survey accessibility and reporting.
- Updated iOS Airship SDK to 16.11.3
- Updated Android Airship SDK to 16.9.1
- Fixed Contact update merge order, resolving a Preference Center bug that could lead to unexpected subscription states in some circumstances.
- Improved Scene/Survey accessibility and fixed a reporting bug related to form display events.

Release 14.9.1

---

urbanairship-cordova/src/ios/UAMessageViewController.m

Fixes the delete button not dismissing the message center. This just overrides the button and calls through to the original method.

Dismiss message view on delete

---

CHANGELOG.md
urbanairship-accengage-cordova/package.json
urbanairship-accengage-cordova/plugin.xml
urbanairship-cordova/package.json
urbanairship-cordova/plugin.xml
urbanairship-cordova/src/android/PluginManager.java
urbanairship-hms-cordova/package.json
urbanairship-hms-cordova/plugin.xml

Fixes a crash on Android if takeOff is called with invalid config. We already validate the config on iOS so this is just an Android issue. Logging/error could be improved but I believe thats already the case in the proxy framework, so this is a quick fix for now until we move cordova over to the proxy.

Release 14.10.1

---

MIGRATION.md
config_sample.xml
cordova-airship-hms/package.json
cordova-airship-hms/plugin.xml
cordova-airship/package.json
cordova-airship/plugin.xml
scripts/check_plugin_version.sh
scripts/update_version.sh

Update plugin id
The error will be fixed
How to reproduce
See 
https://github.com/MaximBelov/urbanairship-cordova/blob/15.0.0-restore-plugin/cordova-id-issue/reproduce.sh
```bash 
./cordova-id-issue/reproduce.sh
```
Failed to restore plugin "cordova-airship". You might need to try adding it again. Error: Error: Command failed with exit code 1: npm view cordova-airship --json
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/cordova-airship - Not found
add to package.json
"@ua/cordova-airship": "github:MaximBelov/urbanairship-cordova#15.0.0-custom",

fix: Failed to restore plugin "cordova-airship"

---

Example/index.html
MIGRATION.md
cordova-airship/src/ios/AirshipCordova.swift
cordova-airship/types/index.d.ts
cordova-airship/www/Airship.js

1. Bug fix
2. Airship.contact.getNamedUserId should return an empty string "" instead "OK"
3. Airship.channel.getChannelId should return an empty string "" instead "OK"
Should fix a lot of errors

15.0.0 Issues

---

CHANGELOG.md
cordova-airship-hms/package.json
cordova-airship-hms/plugin.xml
cordova-airship/package-lock.json
cordova-airship/package.json
cordova-airship/plugin.xml
cordova-airship/src/android/AirshipCordova.kt
cordova-airship/src/android/AirshipCordovaVersion.kt
cordova-airship/src/android/build-extras.gradle
cordova-airship/src/ios/AirshipCordova.swift
cordova-airship/src/ios/AirshipCordovaVersion.swift
cordova-airship/types/index.d.ts
scripts/update_version.sh

Still need new proxy and update iOS quiet time settings

Release 15.2.0
